package io.agora.chatroom.compose.chatmessagelist

import io.agora.chatroom.service.ChatMessage
import io.agora.chatroom.service.GiftEntityProtocol

/**
 * Represents the type of an item that we're showing in the message list.
 */
sealed class ComposeMessageListItemState


/**
 * Represents a Joined Chatroom.
 *
 * @param message customer message.
 */
data class JoinedMessageState(val message: ChatMessage) : ComposeMessageListItemState()

/**
 * Represents a message generated by a system event, such as updating the channel or muting a user.
 *
 * @param gift The message to show.
 */
data class GiftMessageState(
    val message: ChatMessage,
    val gift: GiftEntityProtocol
) : ComposeMessageListItemState()

/**
 * Represents each message item we show in the list of messages.
 *
 * @param message The message to show.
 */
data class ComposeMessageItemState(
    val message: ChatMessage,
    val focusState: MessageFocusState? = null,
) : ComposeMessageListItemState()



enum class ComposeItemType{
    NORMAL,
    ITEM_JOIN,
    ITEM_GIFT,
}