package io.agora.chatroom.ui.compose

import io.agora.chatroom.service.ChatMessage
import io.agora.chatroom.ui.compose.chatmessagelist.MessageFocusState

/**
 * Represents the type of an item that we're showing in the message list.
 */
public sealed class ComposeMessageListItemState


/**
 * Represents a Joined Chatroom.
 *
 * @param message customer message.
 */
public data class JoinedMessageState(val message: ChatMessage) : ComposeMessageListItemState()

/**
 * Represents a message generated by a system event, such as updating the channel or muting a user.
 *
 * @param message The message to show.
 */
public data class GiftMessageState(val message: ChatMessage) : ComposeMessageListItemState()

/**
 * Represents each message item we show in the list of messages.
 *
 * @param message The message to show.
 */
public data class ComposeMessageItemState(
    val message: ChatMessage,
    val focusState: MessageFocusState? = null,
) : ComposeMessageListItemState()



enum class ComposeItemType{
    NORMAL,
    ITEM_JOIN,
}